name: Run Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo my acces key id ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo my secret accces key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo my api token ${{ secrets.TF_API_TOKEN }} 